server.port: 9006

spring.application.name: EVENT-SOURCE-CQRS-AXON

spring.datasource.url: jdbc:postgresql://localhost:5432/CQRSEventService
spring.datasource.driverClassName: org.postgresql.Driver
spring.datasource.username: postgres
spring.datasource.password: password
spring.jpa.show-sql: true

spring.jpa.hibernate.ddl-auto: update

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.data.jpa.repositories.enabled: true
logging.level.org.springframework.web: INFO
